[package]
name = "tectonic_py"
version = "0.1.1"
edition = "2024"

[lib]
name = "tectonic_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }

[dependencies.tectonic]
version = "0.15.0"
features = ["external-harfbuzz"]
