name: Build Python Wheel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build wheel inside Docker
        run: |
          docker build --output dist --tag wheel-builder .

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: python-wheel
          path: dist/dist/*.whl
